export enum EmploymentSince {
  LESS_THAN_SIX_MONTHS = 0,
  BETWEEN_SIX_MONTHS_AND_ONE_YEAR = 1,
  BETWEEN_ONE_AND_TWO_YEARS = 2,
  BETWEEN_TWO_AND_THREE_YEARS = 3,
  BETWEEN_THREE_AND_FOUR_YEARS = 4,
  BETWEEN_FOUR_AND_FIVE_YEARS = 5,
  BETWEEN_FIVE_AND_TEN_YEARS = 6,
  MORE_THAN_TEN_YEARS = 7,
}
