export enum LoanObjectives {
  AJUDAR_UMA_OUTRA_PESSOA_DA_FAMILIA = 0,
  BELEZA_E_SAUDE = 1,
  COMECAR_UM_NOVO_NEGOCIO = 2,
  COMPRAR_CONSERTAR_UM_CARRO = 3,
  COMPRAR_REFORMAR_UMA_CASA = 4,
  EDUCACAO = 5,
  EVENTOS_FESTAS = 6,
  FAZER_COMPRAS = 7,
  FERIAS_VIAGENS = 8,
  PAGAR_CONTAS = 9,
  PAGAR_OUTRAS_DIVIDAS = 10,
  OUTRAS = 11,
}
