export enum AccountType {
  CONTA_CORRENTE_INDIVIDUAL = 'CONTA_CORRENTE_INDIVIDUAL',
  CONTA_CORRENTE_CONJUNTA = 'CONTA_CORRENTE_CONJUNTA',
  CONTA_POUPANCA_CONJUNTA = 'CONTA_POUPANCA_CONJUNTA',
  CONTA_POUPANCA_INDIVIDUAL = 'CONTA_POUPANCA_INDIVIDUAL'
}
