export enum CreditStatus {
  PRE_PROCESSAMENTO = 0,
  PRE_APROVADO = 1,
  PENDENTE = 2,
  AGUARDANDO_DOCUMENTOS = 3,
  EM_ANALISE_MANUAL = 4,
  EM_ANALISE_OPERACIONAL = 5,
  EM_ANALISE_DOCUMENTAL = 6,
  CONTRATADO = 7,
  LIBERADO = 8,
  REPROVADO = 9,
  EXPIRADO = 10,
}
