export enum CreditCardBenefits {
  ANUIDADE_GRATIS = 'ANUIDADE_GRATIS',
  MILHAS_AERIAS = 'MILHAS_AERIAS',
  DESCONTOS = 'DESCONTOS',
  CONTA_DIGITAL = 'CONTA_DIGITAL',
  PROGRAMAS_DE_VANTAGENS = 'PROGRAMAS_DE_VANTAGENS'
}
