export enum CreditStatus {
  PRE_PROCESSAMENTO = 'PRE_PROCESSAMENTO',
  PRE_APROVADO = 'PRE_APROVADO',
  PENDENTE = 'PENDENTE',
  AGUARDANDO_DOCUMENTOS = 'AGUARDANDO_DOCUMENTOS',
  EM_ANALISE_MANUAL = 'EM_ANALISE_MANUAL',
  EM_ANALISE_OPERACIONAL = 'EM_ANALISE_OPERACIONAL',
  EM_ANALISE_DOCUMENTAL = 'EM_ANALISE_DOCUMENTAL',
  CONTRATADO = 'CONTRATADO',
  LIBERADO = 'LIBERADO',
  REPROVADO = 'REPROVADO',
  EXPIRADO = 'EXPIRADO'
}
