export enum Education {
  NAO_ALFABETIZADO = 0,
  ENSINO_FUNDAMENTAL_INCOMPLETO = 1,
  ENSINO_FUNDAMENTAL_COMPLETO = 2,
  ENSINO_MEDIO_INCOMPLETO = 3,
  ENSINO_MEDIO_COMPLETO = 4,
  ENSINO_SUPERIOR_INCOMPLETO = 5,
  ENSINO_SUPERIOR_COMPLETO = 6,
  POS_GRADUACAO = 7,
}
