export enum Education {
  NAO_ALFABETIZADO = 'NAO_ALFABETIZADO',
  ENSINO_FUNDAMENTAL_INCOMPLETO = 'ENSINO_FUNDAMENTAL_INCOMPLETO',
  ENSINO_FUNDAMENTAL_COMPLETO = 'ENSINO_FUNDAMENTAL_COMPLETO',
  ENSINO_MEDIO_INCOMPLETO = 'ENSINO_MEDIO_INCOMPLETO',
  ENSINO_MEDIO_COMPLETO = 'ENSINO_MEDIO_COMPLETO',
  ENSINO_SUPERIOR_INCOMPLETO = 'ENSINO_SUPERIOR_INCOMPLETO',
  ENSINO_SUPERIOR_COMPLETO = 'ENSINO_SUPERIOR_COMPLETO',
  POS_GRADUACAO = 'POS_GRADUACAO'
}
