export enum EmploymentSince {
  LESS_THAN_SIX_MONTHS = 'LESS_THAN_SIX_MONTHS',
  BETWEEN_SIX_MONTHS_AND_ONE_YEAR = 'BETWEEN_SIX_MONTHS_AND_ONE_YEAR',
  BETWEEN_ONE_AND_TWO_YEARS = 'BETWEEN_ONE_AND_TWO_YEARS',
  BETWEEN_TWO_AND_THREE_YEARS = 'BETWEEN_TWO_AND_THREE_YEARS',
  BETWEEN_THREE_AND_FOUR_YEARS = 'BETWEEN_THREE_AND_FOUR_YEARS',
  BETWEEN_FOUR_AND_FIVE_YEARS = 'BETWEEN_FOUR_AND_FIVE_YEARS',
  BETWEEN_FIVE_AND_TEN_YEARS = 'BETWEEN_FIVE_AND_TEN_YEARS',
  MORE_THAN_TEN_YEARS = 'MORE_THAN_TEN_YEARS'
}
