export enum HomeType {
  ALUGADA = 'ALUGADA',
  PARENTES = 'PARENTES',
  FUNCIONAL = 'FUNCIONAL',
  PROPRIA_QUITADA = 'PROPRIA_QUITADA',
  PROPRIA_FINANCIADA = 'PROPRIA_FINANCIADA',
  OUTROS = 'OUTROS'
}
