export enum IdentityType {
  RG = 'RG',
  CNH = 'CNH',
  PASSAPORTE = 'PASSAPORTE',
  CARTEIRA_CRC = 'CARTEIRA_CRC',
  CARTEIRA_CREA = 'CARTEIRA_CREA',
  CARTEIRA_OAB = 'CARTEIRA_OAB',
  CARTEIRA_CRE = 'CARTEIRA_CRE'
}
