export enum LoanObjectives {
  AJUDAR_UMA_OUTRA_PESSOA_DA_FAMILIA = 'AJUDAR_UMA_OUTRA_PESSOA_DA_FAMILIA',
  BELEZA_E_SAUDE = 'BELEZA_E_SAUDE',
  COMECAR_UM_NOVO_NEGOCIO = 'COMECAR_UM_NOVO_NEGOCIO',
  COMPRAR_CONSERTAR_UM_CARRO = 'COMPRAR_CONSERTAR_UM_CARRO',
  COMPRAR_REFORMAR_UMA_CASA = 'COMPRAR_REFORMAR_UMA_CASA',
  EDUCACAO = 'EDUCACAO',
  EVENTOS_FESTAS = 'EVENTOS_FESTAS',
  FAZER_COMPRAS = 'FAZER_COMPRAS',
  FERIAS_VIAGENS = 'FERIAS_VIAGENS',
  PAGAR_CONTAS = 'PAGAR_CONTAS',
  PAGAR_OUTRAS_DIVIDAS = 'PAGAR_OUTRAS_DIVIDAS',
  OUTRAS = 'OUTRAS'
}
