export enum Occupation {
  APOSENTADO = 'APOSENTADO',
  PENSIONISTA = 'PENSIONISTA',
  AUTONOMO = 'AUTONOMO',
  EMPRESARIO = 'EMPRESARIO',
  PROFISSIONAL_LIBERAL = 'PROFISSIONAL_LIBERAL',
  ASSALARIADO = 'ASSALARIADO',
  FUNCIONARIO_PUBLICO = 'FUNCIONARIO_PUBLICO',
  DESEMPREGADO = 'DESEMPREGADO'
}
