export enum PipelineStatus {
  SIGNUP_ANALISIS = 'SIGNUP_ANALISIS',
  SIGNUP_COMPLETED = 'SIGNUP_COMPLETED',
  SIGNUP_DENIED = 'SIGNUP_DENIED',
  PROPOSAL_ANALISIS = 'PROPOSAL_ANALISIS',
  PROPOSAL_CREATED = 'PROPOSAL_CREATED',
  PROPOSAL_DENIED = 'PROPOSAL_DENIED'
}
