export enum RelationshipStatus {
  CASADO = 'CASADO',
  DIVORCIADO = 'DIVORCIADO',
  VIUVO = 'VIUVO',
  SEPARADO = 'SEPARADO',
  SOLTEIRO = 'SOLTEIRO',
  COMPANHEIRO = 'COMPANHEIRO',
  UNIAO_ESTAVEL = 'UNIAO_ESTAVEL',
  SEPARADO_JUDICIALMENTE = 'SEPARADO_JUDICIALMENTE'
}
