export enum WorkingCapitalLoanObjectives {
  CAPITAL_DE_GIRO = 'CAPITAL_DE_GIRO',
  RENEGOCIACAO_DE_DIVIDAS = 'RENEGOCIACAO_DE_DIVIDAS',
  MARKETING_E_VENDAS = 'MARKETING_E_VENDAS',
  EXPANSAO_DE_NEGOCIOS = 'EXPANSAO_DE_NEGOCIOS',
  EXPANSAO = 'EXPANSAO',
  ESTOQUE = 'ESTOQUE',
  REFORMA = 'REFORMA',
  USO_PESSOAL = 'USO_PESSOAL'
}
