name: Deploy on NPM

on:
  push:
    branches:
      - releases/*

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@Fitbank-Pagamentos-Eletronicos'
      - run: npm ci && npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN_DEPLOY}}
